var lang = {
 "cancel": "取消",
 "date": "日期",
 "dates": {
  "days": [
   "星期日",
   "星期一",
   "星期二",
   "星期三",
   "星期四",
   "星期五",
   "星期六",
   "星期日"
  ],
  "daysMin": [
   "日",
   "一",
   "二",
   "三",
   "四",
   "五",
   "六",
   "日"
  ],
  "daysShort": [
   "日",
   "一",
   "二",
   "三",
   "四",
   "五",
   "六",
   "日"
  ],
  "meridiem": [
   "上午",
   "下午"
  ],
  "months": [
   "一月",
   "二月",
   "三月",
   "四月",
   "五月",
   "六月",
   "七月",
   "八月",
   "九月",
   "十月",
   "十一月",
   "十二月"
  ],
  "monthsShort": [
   "一",
   "二",
   "三",
   "四",
   "五",
   "六",
   "七",
   "八",
   "九",
   "十",
   "十一",
   "十二"
  ],
  "suffix": [
   "",
   "",
   "",
   ""
  ],
  "today": "今天"
 },
 "day": "日",
 "hour": "時",
 "minute": "分",
 "ok": "確定",
 "save": "儲存",
 "search": "查詢",
 "send": "送出",
 "startdate": "開始日期",
 "starttime": "開始時間",
 "status": "狀態",
 "store": "儲存",
 "validateForm": {
  "required": "請輸入資料",
  "remote": "請修正",
  "email": "請輸入合法的email",
  "url": "請輸入合法的網址",
  "date": "请输入合法的日期",
  "dateISO": "請輸入合法的日期 (ISO).",
  "number": "請輸入合法的數字",
  "digits": "只能輸入整數",
  "creditcard": "請輸入合法的信用卡號",
  "equalTo": "請再次輸入相同的值",
  "accept": "請輸入擁有合法後綴名的字符串",
  "maxlength": "請輸入一個長度最多是{0} 的字符串",
  "minlength": "請輸入一個長度最少是{0} 的字符串",
  "rangelength": "請輸入一個長度介於{0} 和{1} 之間的字符串",
  "range": "請輸入一個介於{0} 和{1} 之間的值",
  "max": "請輸入一個最大為{0} 的值",
  "min": "請輸入一個最小為{0} 的值",
  "companyId": "請輸入公司統一編號",
  "invalidCompanyId": "不合法的統一編號",
  "domain": "請輸入公司的domain網址，如：exp.com.tw",
  "userId": "請輸入有效帳號",
  "geoloc": "請先座標定位"
 },
 "month": "月份",
 "form": {
  "id": "表單編號",
  "name": "表單名稱",
  "creator": "創建者",
  "create_date": "創建時間",
  "modify_date": "最新修改時間",
  "list": "表單列表",
  "custom_form": "自訂表單",
  "component": "單一元件",
  "tuple": "組合元件",
  "label": "說明文字",
  "text": "單行文字",
  "textarea": "多行文字",
  "week": "星期",
  "checkbox": "多選",
  "radio": "單選",
  "date": "日期",
  "time": "時間",
  "range": "數值選單",
  "group": "群組",
  "row": "同列群組",
  "vertical": "直式",
  "horizontal": "橫式",
  "dropdownlist": "下拉式",
  "phone": "電話",
  "email": "電子郵件",
  "address": "地址",
  "county": "縣市",
  "area": "鄉鎮市區",
  "village": "村里",
  "edit": "編輯",
  "plz_input_form_name": "請輸入表單名稱!",
  "exist": "此表單已含有資料不得更改，新建另一筆?",
  "setting_error": "設定錯誤",
  "custom": "自訂",
  "custom_cant_null": "自訂選項不能為空!",
  "col_name": "標題",
  "def": "預設值",
  "display_style": "顯示方式",
  "option": "選項清單",
  "range_setting": "範圍設定",
  "min": "最小值",
  "max": "最大值",
  "interval": "間隔",
  "apply": "設定",
  "length": "長度",
  "fromto": "起訖",
  "required": "必填",
  "readonly": "唯獨",
  "save": "儲存",
  "re_login": "帳號已被登出，請重新登入!",
  "not_completed": "表單內容尚未完整!",
  "modify_user": "修改者",
  "illegal_value": "欄位內容不完整，請輸入有效的值",
  "group_is_empty": "群組內容不得為空",
  "cant_null": "範圍需在-1000.0~1000.0",
  "keycode_cant_null": "單選/多選的自訂選項不得為空，請確認！",
  "interval_cant_null": "間隔數值為必填",
  "component_prop": "元件內容",
  "enter_option": "請輸入選項",
  "interval_cant_zero": "間隔數值不得為0",
  "interval_cant_negative": "間隔數值須為正數",
  "decimal_one": "數值僅允許小數點後一位",
  "maxlength_err_msg": "您必須輸入介於 1 到 50 之間的值",
  "min_greaterthan_max_err": "最大值需大於最小值",
  "interval_err": "間隔值不得超過最大值與最小值兩數差距",
  "rangeOverflow": "",
  "rangeUnderflow": "必須大於或等於",
  "request_head": "請填寫",
  "request_tail": "這個欄位"
 },
  "btn":{
   "clean": "clean"
 }
};
