var lang = {
 "cancel": "Cancel",
 "date": "Date",
 "dates": {
  "days": [
   "星期日",
   "星期一",
   "星期二",
   "星期三",
   "星期四",
   "星期五",
   "星期六",
   "星期日"
  ],
  "daysMin": [
   "日",
   "一",
   "二",
   "三",
   "四",
   "五",
   "六",
   "日"
  ],
  "daysShort": [
   "日",
   "一",
   "二",
   "三",
   "四",
   "五",
   "六",
   "日"
  ],
  "meridiem": [
   "上午",
   "下午"
  ],
  "months": [
   "一月",
   "二月",
   "三月",
   "四月",
   "五月",
   "六月",
   "七月",
   "八月",
   "九月",
   "十月",
   "十一月",
   "十二月"
  ],
  "monthsShort": [
   "一",
   "二",
   "三",
   "四",
   "五",
   "六",
   "七",
   "八",
   "九",
   "十",
   "十一",
   "十二"
  ],
  "suffix": [
   "",
   "",
   "",
   ""
  ],
  "today": "Today"
 },
 "day": "Day",
 "hour": "Hour",
 "minute": "Minute",
 "ok": "OK",
 "save": "SAVE",
 "search": "Search",
 "send": "Send",
 "startdate": "開始日期",
 "starttime": "開始時間",
 "status": "Status",
 "store": "Store",
 "validateForm": {
  "required": "請輸入資料",
  "remote": "請修正",
  "email": "請輸入合法的email",
  "url": "請輸入合法的網址",
  "date": "请输入合法的日期",
  "dateISO": "請輸入合法的日期 (ISO).",
  "number": "請輸入合法的數字",
  "digits": "只能輸入整數",
  "creditcard": "請輸入合法的信用卡號",
  "equalTo": "請再次輸入相同的值",
  "accept": "請輸入擁有合法後綴名的字符串",
  "maxlength": "請輸入一個長度最多是{0} 的字符串",
  "minlength": "請輸入一個長度最少是{0} 的字符串",
  "rangelength": "請輸入一個長度介於{0} 和{1} 之間的字符串",
  "range": "請輸入一個介於{0} 和{1} 之間的值",
  "max": "請輸入一個最大為{0} 的值",
  "min": "請輸入一個最小為{0} 的值",
  "companyId": "請輸入公司統一編號",
  "invalidCompanyId": "不合法的統一編號",
  "domain": "請輸入公司的domain網址，如：exp.com.tw",
  "userId": "請輸入有效帳號",
  "geoloc": "請先座標定位"
 },
 "month": "Month",
 "form": {
  "id": "ID",
  "name": "Name",
  "creator": "Creator",
  "create_date": "創建時間",
  "modify_date": "最新修改時間",
  "list": "表單列表",
  "custom_form": "自訂表單",
  "component": "Component",
  "tuple": "Tuple",
  "label": "Lable",
  "text": "Text",
  "textarea": "Textarea",
  "week": "day of week",
  "checkbox": "Checkbox",
  "radio": "Radio",
  "date": "Date",
  "time": "Time",
  "range": "Range",
  "group": "Group",
  "row": "Row",
  "vertical": "Vertical",
  "horizontal": "Horizontal",
  "dropdownlist": "Dropdownlist",
  "phone": "Phone",
  "email": "Email",
  "address": "Address",
  "county": "County",
  "area": "Area",
  "village": "Village",
  "edit": "Edit",
  "plz_input_form_name": "Please enter the name of the form!",
  "exist": "此表單已含有資料不得更改，新建另一筆?",
  "setting_error": "設定錯誤",
  "custom": "Custom",
  "custom_cant_null": "adio / Checkbox of custom options can not be empty, please confirm!",
  "col_name": "Column Name",
  "def": "Def",
  "display_style": "Style",
  "option": "Optional",
  "range_setting": "Range setting",
  "min": "Min",
  "max": "Max",
  "interval": "Interval",
  "apply": "Apply",
  "length": "Length",
  "fromto": "From...To",
  "required": "Required",
  "readonly": "Readonly",
  "save": "Save",
  "re_login": "帳號已被登出，請重新登入!",
  "not_completed": "表單內容尚未完整!",
  "modify_user": "修改者",
  "illegal_value": "Illegal value",
  "group_is_empty": "group can not be null",
  "cant_null": "The range must be -1000.0 ~ 1000.0",
  "keycode_cant_null": "Radio / Checkbox of custom options can not be empty, please confirm!",
  "interval_cant_null": "The interval value is required!",
  "component_prop": "Component properties",
  "enter_option": "Enter an option",
  "interval_cant_zero": "The interval value can not be zero.",
  "interval_cant_negative": "The interval value must be positive!",
  "decimal_one": "The value only allows one decimal place",
  "maxlength_err_msg": "maxlength must be between 1 and 50",
  "min_greaterthan_max_err": "The Max value must be greater than the Min value",
  "interval_err": "The interval value should not exceed the maximum and minimum two number of gaps",
  "rangeOverflow": "",
  "rangeUnderflow": "必須大於或等於",
  "request_head": "請填寫",
  "request_tail": "這個欄位"
 },
  "btn":{
   "clean": "Clean"
 }
};
